### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [cskorenko/prj-rev-bwfs-dasmoto#5]
Summary: Satisfactory

Good job with your code! I really like the use of whitespace! Makes your code very easy to read! Also, good decisions on the classes and ids name. It makes it very clear what its purpose is and makes grouping your sections very effective. These organizational skills come in handy as you expand your code. Finally, good decision to save images locally! Saving images adds to the stability of your website because your website is not reliant on the link to be valid all the time. Great start to the Ready program! 

I included a few notes in both the html file for you to think more critically about. First, make sure to specify CSS attributes like 'span' with selectors like id and classes. This will help you reuse your code and gives it more flexibility. Next, make sure to think about how your images should respond to different screen sizes. Right now, it becomes really large and takes up nearly half the screen when the screen gets narrow. Try setting the width constraint to a percentage of the screen or use mobile resizing to change height based on width of the screen.

**Comment by cskorenko** [comment]
Thank you. Didn't think about the image sizing or defining the span. I appreciate the encouragement and feedback. I'm really enjoying the course so far.
